# Generated by Django 6.0.1 on 2026-02-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_category_options_category_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="Изображение"
            ),
        ),
    ]
