# Generated by Django 6.0.1 on 2026-03-05 13:20

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_options_product_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=tinymce.models.HTMLField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=tinymce.models.HTMLField(blank=True, verbose_name="Описание"),
        ),
    ]
